### ISSUE TITLE
specifying packages does not work

### ISSUE THREAD

**Issue by michaelBelsanti** [selfuryon/nix-update-action#1]
I am trying to add this action to a project, but specifying packages as shown in the README file does not seem to be working correctly. Specifying blacklisted packages does work and can be used as a workaround in the meantime.

This is the workflow file I am using:
<details><summary>Details</summary>
<p>

```
name: "Update packages"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *" # https://crontab.guru/#0_10_*_*_0
jobs:
  updateFlakePackages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - name: Update flake packages
        uses: selfuryon/nix-update-action@v1.0.0
        with:
          packages: "slippi-netplay,slippi-launcher"

``` 

</p>
</details>
